### ISSUE TITLE
Black images when i download tiles from test.py

### ISSUE THREAD

**Issue by FranckzA** [Jimut123/jimutmap#24]
**Describe the bug**
Hello, i have been trying to use the jimutmap, that i think is an interesting python script for geospatial analysis, i already installed in windows 11 and ubuntu, following all of the steps and properly installing each dependency with their correspondent version (i.e. numpy, opencv, selenium, etc)... the problem that i have been facing in the last days is when i download the tiles from the test.py, i only download black images also for the street maps, i tried different zoom options, and modifying any other parameters, but, same problem, any recommendation?, many thanks in advance for your support... best regards

**Screenshots**
![Screenshot from 2023-02-02 14-49-47](https://user-images.githubusercontent.com/107002355/216421718-843c9039-4ef0-4391-9c31-4e5ed3cea7f8.png)

**Desktop (please complete the following information):**
 - Ubuntu 20.04 and windows 11
 - Chrome
 - Python version 3.7 and python version 3.9

**Comment by FranckzGithub** [comment]
I am highly interested in download images from Bolivia using this:

a = api(min_lat_deg = -17.91, max_lat_deg = -17.90, min_lon_deg = -67.01, max_lon_deg = -67.00, zoom = 19,verbose = False,threads_ = 5,container_dir = "Cochabamba")
a.download()

But still having same problem =(, black images...

**Comment by HaneenAloufi** [comment]
did you manage to solve the issue with the black images ? 'cause i'm having the same issue

**Comment by FranckzGithub** [comment]
not yet, i guess the reason is the broken links of apple maps.... because some areas are working well, but any other are not working, for example this area download all tiles:

from jimutmap import api
a=api(42.086312,42.144378,24.626069,24.761338,zoom=19,verbose=False,threads_=5)
a.download()

I am still looking for a solution, for now this github library is working for me, is another option : https://github.com/doersino/gomati
And it is working very well, it have their limitations.

**Comment by Jimut123** [comment]
Hi, this is a common issue rn; I have to look into this (not sure when I will get the proper time, since this may be the issue with satellites.pro website, maybe some tiles are missing in there with the zoom range you mentioned). If you find any solution, don't hesitate to do a PR.
